import { useEffect, useId, useRef, useState, type CSSProperties } from "react";
import { allocateByWeights, STARTUP_IDS, type MarketObservation, type PublicEventResponse, type SessionResponse, type StartupId } from "@startup-game/shared";
import { useI18n, type MessageKey } from "./i18n.js";
import { formatMoney, formatMoneyExact, formatMoneySignedExact, formatPercent } from "./format.js";

export type AmountDraft = Record<StartupId, string>;
export const zeroDraft = (): AmountDraft => Object.fromEntries(STARTUP_IDS.map(id => [id, "0"])) as AmountDraft;
export function centsToInput(cents: number): string { return `${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, "0")}`; }
export function parseDollarInput(value: string): number | null {
  const match = /^(\d+)(?:[.,](\d{0,2}))?$/.exec(value.trim());
  if (!match) return null;
  const n = Number(match[1]) * 100 + Number((match[2] ?? "").padEnd(2, "0"));
  return Number.isSafeInteger(n) && n >= 0 ? n : null;
}
export function initialDraft(s: SessionResponse): AmountDraft { return Object.fromEntries(STARTUP_IDS.map(id => [id, centsToInput(s.portfolio.startupAmountsCents[id] ?? 0)])) as AmountDraft; }
export const COMPANY_META: Record<StartupId, { color: string; tint: string; sector: MessageKey; description: MessageKey; path: string }> = {
  NovaMind: { color: "#6458c7", tint: "#f0edff", sector: "sectorNovaMind", description: "companyNovaMind", path: "M7 18V7h4l10 17V7h4v25h-4L11 15v17H7" },
  MedFlow: { color: "#3686aa", tint: "#eaf5fa", sector: "sectorMedFlow", description: "companyMedFlow", path: "M16 6h7v10h10v7H23v10h-7V23H6v-7h10Z" },
  VoltX: { color: "#ab751d", tint: "#fff5df", sector: "sectorVoltX", description: "companyVoltX", path: "m23 4-15 20h11l-2 12 15-20H21Z" },
  GreenBox: { color: "#548184", tint: "#edf5f4", sector: "sectorGreenBox", description: "companyGreenBox", path: "m6 13 14-7 14 7v15l-14 7-14-7Zm0 0 14 7 14-7M20 20v15" },
  AgroPulse: { color: "#a06e46", tint: "#faf0e5", sector: "sectorAgroPulse", description: "companyAgroPulse", path: "M20 35V18M20 24C8 24 5 17 6 9c9 0 14 5 14 15Zm0-6C20 8 26 5 34 6c0 9-5 14-14 12" },
  OrbitLink: { color: "#5676c0", tint: "#ecf0fb", sector: "sectorOrbitLink", description: "companyOrbitLink", path: "m15 13 12 12-7 7L8 20Zm-6-5 6 5-7 7-6-6Zm18 17 6 5-7 7-6-5ZM25 7a9 9 0 0 1 9 9M25 2a14 14 0 0 1 14 14" },
};
export function BrandIcon({ id, size = 40 }: { id: StartupId; size?: number }) {
  const m = COMPANY_META[id]; return <span className="company-mark" style={{ background: m.tint, color: m.color, width: size, height: size }}><svg width={size * .64} height={size * .64} viewBox="0 0 40 40" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={m.path}/></svg></span>;
}
export function ProductArt({ id }: { id: StartupId }) {
  const uid = useId(); const m = COMPANY_META[id];
  return <svg className="product-art" viewBox="0 0 220 94" aria-hidden="true" style={{ color: m.color }}>
    <defs><linearGradient id={uid} x2="1" y2="1"><stop stopColor={m.tint}/><stop offset="1" stopColor="white"/></linearGradient></defs>
    <rect width="220" height="94" rx="16" fill={`url(#${uid})`}/><circle cx="175" cy="30" r="43" fill={m.color} opacity=".04"/>
    {id === "NovaMind" ? <g><rect x="45" y="20" width="125" height="59" rx="8" fill="white" stroke="currentColor" strokeOpacity=".25"/><path d="M46 33h122" stroke="currentColor" opacity=".2"/><circle cx="55" cy="27" r="2" fill="currentColor"/><rect x="57" y="43" width="25" height="24" rx="4" fill="currentColor" opacity=".15"/><path d="M95 48h60M95 57h45M95 66h52" stroke="currentColor" strokeWidth="4" strokeLinecap="round" opacity=".3"/></g>
      : id === "MedFlow" ? <g><rect x="54" y="17" width="113" height="61" rx="8" fill="white" stroke="currentColor" strokeOpacity=".25"/><path d="M65 51h18l6-15 12 30 9-23 7 8h36" stroke="currentColor" strokeWidth="3" fill="none"/><path d="M65 27h28M133 69h23" stroke="currentColor" strokeWidth="3" opacity=".25"/></g>
      : id === "VoltX" ? <g>{[0,1,2].map(i=><g key={i} transform={`translate(${65+i*32}, 20)`}><rect width="25" height="56" rx="5" fill="white" stroke="currentColor" strokeOpacity=".3"/><rect x="4" y="9" width="17" height="32" rx="3" fill="currentColor" opacity={.12+i*.12}/><path d="M8 49h9" stroke="currentColor" strokeWidth="2"/></g>)}</g>
      : id === "GreenBox" ? <g stroke="currentColor" strokeLinejoin="round"><path d="m110 16 46 24v32l-46 15-46-24V32Z" fill="white" strokeOpacity=".3"/><path d="m64 32 46 24 46-16M110 56v31m-20-68 47 25v18" fill="none" strokeOpacity=".5"/><path d="M69 71h-19m11 7H42" opacity=".2"/></g>
      : id === "AgroPulse" ? <g><path d="M30 77c50-26 105-25 160-1M30 85c60-23 104-18 160-1" stroke="currentColor" opacity=".2" fill="none"/><path d="M111 72V34c-19 0-25-10-26-22 19 0 26 10 26 22 0-20 12-23 28-22-1 16-12 22-28 22" stroke="currentColor" strokeWidth="2.5" fill="white"/><rect x="153" y="44" width="11" height="29" rx="4" fill="currentColor" opacity=".25"/><circle cx="159" cy="44" r="4" fill="currentColor"/></g>
      : <g transform="translate(110 46) rotate(-25)"><rect x="-18" y="-16" width="36" height="32" rx="5" fill="white" stroke="currentColor" strokeOpacity=".5"/><rect x="-66" y="-12" width="42" height="24" rx="2" fill="currentColor" opacity=".25"/><rect x="24" y="-12" width="42" height="24" rx="2" fill="currentColor" opacity=".25"/><path d="M-52-12v24m14-24v24m76-24v24m14-24v24M0-16v-10m-8-5c3 5 13 5 16 0" stroke="currentColor" strokeOpacity=".7" fill="none"/></g>}
  </svg>;
}
export function AnimatedMoney({ cents, from, exact = false }: { cents: number; from?: number; exact?: boolean }) {
  const { language } = useI18n(); const [shown, setShown] = useState(from ?? cents); const previous = useRef(from ?? cents);
  useEffect(() => {
    if (document.documentElement.dataset.motion === "off" || window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setShown(cents); previous.current = cents; return; }
    const start = performance.now(); const initial = previous.current; let frame = 0;
    const step = (now: number) => { const t = document.documentElement.dataset.motion === "off" ? 1 : Math.min(1, (now-start)/750); setShown(Math.round(initial + (cents-initial)*(1-Math.pow(1-t,3)))); if (t<1) frame=requestAnimationFrame(step); };
    frame=requestAnimationFrame(step); previous.current=cents; return()=>cancelAnimationFrame(frame);
  }, [cents]);
  return <span aria-label={formatMoneyExact(cents, language)}><span aria-hidden="true">{exact ? formatMoneyExact(shown, language) : formatMoney(shown, language)}</span></span>;
}
export function LineChart({ values, second, color = "#17664d", large = false, label }: { values: number[]; second?: number[]; color?: string; large?: boolean; label: string }) {
  if (!values.length) return <span className="muted">—</span>;
  const width=420, height=large?160:46, top=12, bottom=height-12;
  const all=[...values,...(second??[])]; const min=second?0:Math.min(...all)*.95, max=Math.max(...all)*1.05;
  const coords=(arr:number[])=>arr.map((v,i)=>`${12+(width-24)*i/Math.max(1,arr.length-1)},${bottom-(v-min)/Math.max(1,max-min)*(bottom-top)}`).join(" ");
  return <svg className={large?"line-chart large":"line-chart"} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}>
    {large&&[.25,.5,.75].map(n=><line key={n} x1="12" x2={width-12} y1={top+n*(bottom-top)} y2={top+n*(bottom-top)} stroke="#e8e9ef" strokeDasharray="4 5"/>)}
    <polyline className="chart-path" points={coords(values)} fill="none" stroke={color} strokeWidth={large?3:2.4} strokeLinecap="round" strokeLinejoin="round"/>
    {second&&<polyline className="chart-path" points={coords(second)} fill="none" stroke="#ab751d" strokeWidth="2.5" strokeDasharray="6 3"/>}
    {large&&values.map((v,i)=>{const [x,y]=coords(values).split(" ")[i]!.split(",");return <circle key={i} cx={x} cy={y} r="3" fill={color}/>;})}
  </svg>;
}
export function Leaderboard({ event }: { event: PublicEventResponse }) {
  const { t, language }=useI18n();
  return <section className="panel leaderboard-panel"><div className="section-heading"><div><h2>{t(event.status==="OPEN"?"leaderboard":"allPlayers")}</h2></div><span className="count-pill">{t("playerCount",{count:event.completedCount})}</span></div>
    {!event.leaderboard.length?<p className="empty-state">{t("noPlayers")}</p>:<ol className="leaderboard-list">{event.leaderboard.map((p,i)=><li className="leaderboard-row" key={i}><span className={`leader-place rank-${p.place}`}>{String(p.place).padStart(2,"0")}</span><span>{p.name}</span><strong>{formatMoneyExact(p.finalCapitalCents,language)}</strong></li>)}</ol>}
  </section>;
}

function CompanyDetails({ company, onClose }: { company: MarketObservation; onClose:()=>void }) {
  const { t,language }=useI18n(); const ref=useRef<HTMLDialogElement>(null);const id=company.startupId,m=COMPANY_META[id];
  useEffect(()=>{const d=ref.current!;const opener=document.activeElement;d.showModal();return()=>{d.close();if(opener instanceof HTMLElement&&opener.isConnected)opener.focus({preventScroll:true});};},[]);
  const history=company.financialHistory; const f=(n:number)=>formatMoney(n,language);
  return <dialog ref={ref} className="details-dialog" onCancel={onClose} aria-labelledby="details-title"><div className="details-body"><button className="close-dialog" onClick={onClose} aria-label={t("closeDetails")}>×</button><BrandIcon id={id} size={56}/><p className="eyebrow">{t(m.sector)}</p><h2 id="details-title">{id}</h2><p className="page-lead">{t(m.description)}</p><ProductArt id={id}/>
    <h3>{t("completeData")}</h3><div className="full-metrics">{([["revenue",company.metrics.revenueThousandsUsd,company.metrics.revenueChangeBps],["customers",company.metrics.customers,company.metrics.customersChangeBps],["expenses",company.metrics.expensesThousandsUsd,company.metrics.expensesChangeBps],["cashReserve",company.metrics.cashReserveThousandsUsd,company.metrics.cashReserveChangeBps]] as const).map(([key,value,change])=><div key={key}><span>{t(key)}{(key==="revenue"||key==="expenses")&&<small> · {t("monthly")}</small>}</span><strong>{new Intl.NumberFormat(language==="ru"?"ru-RU":"en-US").format(value)}{key!=="customers"&&` ${t("thousandUnit")}`}</strong><small>{change===null?"—":formatPercent(change,language)}</small></div>)}</div>
    <h3>{t("whatDataSays")}</h3>{company.analysis.map((a,i)=><p className="insight" key={i}>{a[language]}</p>)}
    <div className="details-kpis"><div><span>{t("margin")}</span><strong>{formatPercent(company.marginBps,language)}</strong></div><div><span>{t("quarterFlow")}</span><strong>{formatMoneySignedExact(company.operatingCashFlowCents,language)}</strong></div></div>
    {company.debtCents>0&&<p className="inline-error">{t("debt")}: {f(company.debtCents)}</p>}
    <h3>{t("businessHistory")}</h3>{history.length>0&&<><div className="chart-legend"><span className="legend-revenue">{t("revenue")}</span><span className="legend-expenses">{t("expenses")}</span></div><LineChart large values={history.map(p=>p.revenueCents)} second={history.map(p=>p.expensesCents)} label={history.map(p=>`${p.period}: ${t("revenue")} ${f(p.revenueCents)}, ${t("expenses")} ${f(p.expensesCents)}`).join("; ")}/><div className="history-table-wrap"><table className="history-table"><thead><tr><th>{t("history")}</th><th>{t("revenue")}</th><th>{t("expenses")}</th><th>{t("cashReserve")}</th></tr></thead><tbody>{history.map(p=><tr key={p.period}><td>{p.period<0?t("pastPeriod",{period:p.period}):p.period===0?t("currentPeriod"):t("previousValue",{round:p.period})}</td><td>{f(p.revenueCents)}</td><td>{f(p.expensesCents)}</td><td>{f(p.cashCents)}</td></tr>)}</tbody></table></div></>}
    <h3>{t("news")}</h3>{company.news.map((n,i)=><article className="news-item" key={i}><div><span>{t(n.source==="company"?"sourceCompany":n.source==="partner"?"sourcePartner":"sourceIndustry")}</span><span className="news-certainty">{t(n.certainty)}</span></div><p>{n.text[language]}</p></article>)}<p className="model-note">{t("modelAssumptions")}</p><button className="secondary-button" onClick={onClose}>{t("closeDetails")}</button>
  </div></dialog>;
}

export function PortfolioBar({ amounts, cash, capital, ids }: { amounts: Record<StartupId,number>; cash:number; capital:number; ids: readonly StartupId[] }) {
  const { t, language }=useI18n(); return <div className="portfolio-bar" role="img" aria-label={[...ids.map(id=>`${id}: ${formatMoneyExact(amounts[id],language)}`),`${t("cash")}: ${formatMoneyExact(cash,language)}`].join("; ")}>{ids.filter(id=>amounts[id]>0).map(id=><span key={id} title={`${id} ${formatMoneyExact(amounts[id],language)}`} style={{width:`${capital?amounts[id]*100/capital:0}%`,background:COMPANY_META[id].color}}/>)}{cash>0&&<span style={{width:`${capital?cash*100/capital:100}%`,background:"#c5c9d5"}}/>}</div>;
}
export function RoundDecision({ session,draft,setDraft,busy,error,onConfirm,savingDraft }: { session:SessionResponse;draft:AmountDraft;setDraft:(d:AmountDraft)=>void;busy:boolean;error:string;onConfirm:(a:Record<StartupId,number>,cash:number)=>void;savingDraft:boolean }) {
  const { t,language }=useI18n();const [details,setDetails]=useState<MarketObservation|null>(null);const [undo,setUndo]=useState<AmountDraft|null>(null);
  const ids=session.startupIds;const parsed=Object.fromEntries(STARTUP_IDS.map(id=>[id,parseDollarInput(draft[id])])) as Record<StartupId,number|null>;
  const inputValid=STARTUP_IDS.every(id=>parsed[id]!==null);const amounts=parsed as Record<StartupId,number>;const total=inputValid?STARTUP_IDS.reduce((s,id)=>s+amounts[id],0):0;const cash=session.capitalCents-total;const valid=inputValid&&Number.isSafeInteger(total)&&cash>=0;
  const commit=(d:AmountDraft)=>{setUndo({...draft});setDraft(d);};
  const change=(id:StartupId,n:number)=>{const others=ids.filter(k=>k!==id).reduce((s,k)=>s+(parsed[k]??0),0);commit({...draft,[id]:centsToInput(Math.max(0,Math.min(n,session.capitalCents-others)))});};
  const assign=(values:number[])=>commit(Object.fromEntries(STARTUP_IDS.map(id=>[id,centsToInput(values[ids.indexOf(id)]??0)])) as AmountDraft);
  const previous=session.roundHistory.at(-1);
  const maxShare=valid&&session.capitalCents?Math.round(Math.max(...ids.map(id=>amounts[id]))*10000/session.capitalCents):0;
  return <main className="app-content game-page"><div className="game-heading"><div><p className="player-caption">{session.name}</p><h1>{t("round",{current:session.currentRound})}</h1></div><div className="round-progress" aria-label={t("round",{current:session.currentRound})}>{[1,2,3].map(n=><span key={n} className={n===session.currentRound?"current":n<session.currentRound?"done":""}>{n<session.currentRound?"✓":n}</span>)}</div><div className="header-capital"><span>{t("capital")}</span><strong><AnimatedMoney cents={session.capitalCents}/></strong></div></div>
    <p className="decision-hint">{t("chooseHint")}</p><div className="game-layout"><section className="company-grid" aria-label={t("marketData")}>{session.decisionMarket?.companies.map(company=>{const id=company.startupId,m=COMPANY_META[id];const metrics=company.metrics;
      return <article className="company-card" key={id} style={{"--company-color":m.color,"--company-tint":m.tint} as CSSProperties}><div className="company-heading"><BrandIcon id={id}/><div><h2>{id}</h2><span>{t(m.sector)}</span></div><button className="detail-button" onClick={()=>setDetails(company)} aria-label={`${t("showDetails")} ${id}`}>↗</button></div><div className="company-story"><p className="company-signal">{company.signal[language]}</p></div><div className="metric-grid"><div className="metric"><span>{t("customers")}</span><strong>{new Intl.NumberFormat(language==="ru"?"ru-RU":"en-US").format(metrics.customers)}</strong>{metrics.customersChangeBps!==null&&<small className="metric-delta">{formatPercent(metrics.customersChangeBps,language)} · {t("metricChange")}</small>}</div><div className="metric"><span>{t("afterCosts")}</span><strong>{formatPercent(company.marginBps,language,false)}</strong><small className="metric-delta">{t("monthly")}</small></div></div>
      <div className="amount-control"><label className="investment-label" htmlFor={`amount-${id}`}>{t("investmentLabel")} <span className="visually-hidden">{id}, {t("amount")}</span></label><div className="amount-input-wrap"><input id={`amount-${id}`} inputMode="decimal" value={draft[id]} disabled={busy} onChange={e=>commit({...draft,[id]:e.target.value})}/><span>$</span></div><button className="cash-button" disabled={!valid||busy||cash<=0} onClick={()=>change(id,(parsed[id]??0)+cash)} aria-label={t("investAllFor",{company:id})}>↗</button></div><div className="quick-actions">{[-50,50].map(n=><button key={n} type="button" disabled={busy||!inputValid||(n>0?cash<=0:(parsed[id]??0)<=0)} onClick={()=>change(id,(parsed[id]??0)+n*100)} aria-label={`${t(n===-50?"down50":"up50")} ${id}`}>{n>0?"+":"−"}50 $</button>)}<details className="amount-options"><summary>{t("moreControls")}</summary><div>{[-100,100].map(n=><button key={n} disabled={busy||!inputValid||(n>0?cash<=0:(parsed[id]??0)<=0)} onClick={()=>change(id,(parsed[id]??0)+n*100)} aria-label={`${t(n===-100?"down100":"up100")} ${id}`}>{n>0?"+":"−"}100 $</button>)}{[25,50,100].map(p=><button key={p} disabled={!valid||busy||cash<=0} aria-label={`${id}: ${p}% ${t("available")}`} onClick={()=>change(id,amounts[id]+Number(BigInt(cash)*BigInt(p)/100n))}>{p}% {t("available")}</button>)}</div></details></div>
      </article>;
    })}</section><aside className="allocation-panel panel"><h2>{t("allocation")}</h2><div className="portfolio-total"><span>{t("available")}</span><strong>{valid?formatMoneyExact(cash,language):"—"}</strong></div>{valid&&<PortfolioBar amounts={amounts} cash={cash} capital={session.capitalCents} ids={ids}/>}
      <div className="allocation-items">{ids.map(id=><div key={id}><span><i style={{background:COMPANY_META[id].color}}/>{id}</span><strong>{valid?formatMoneyExact(amounts[id],language):"—"}</strong><small>{valid&&session.capitalCents?formatPercent(Math.round(amounts[id]*10000/session.capitalCents),language,false):"0%"}</small></div>)}<div className="cash-allocation"><span><i/>{t("unallocated")}</span><strong>{valid?formatMoneyExact(cash,language):"—"}</strong></div></div>
      {maxShare>=6000&&<p className="concentration-note">{t("concentration",{share:formatPercent(maxShare,language,false)})}<small>{t("notForecast")}</small></p>}<div className="portfolio-tools"><button className="secondary-button" disabled={busy} onClick={()=>assign(allocateByWeights(session.capitalCents,ids.map(()=>1)))}>{t("equally")}</button><button className="quiet-button" disabled={busy} onClick={()=>commit(zeroDraft())}>{t("clearAllocation")}</button><button className="quiet-button" disabled={!undo||busy} onClick={()=>{if(undo){setDraft(undo);setUndo(null);}}}>{t("undo")}</button>{previous&&<button className="quiet-button" disabled={busy} onClick={()=>{const v=allocateByWeights(session.capitalCents,[...ids.map(id=>previous.companies.find(c=>c.startupId===id)?.amountCents??0),previous.cashCents]);assign(v);}}>{t("keepWeights")}</button>}</div>
      {!valid&&<p className="inline-error" role="alert">{t(inputValid?"allocationUnbalanced":"allocationInvalid")}</p>}{error&&<p className="inline-error" role="alert">{error}</p>}<button className="primary-button confirm-button" disabled={!valid||busy} onClick={()=>valid&&onConfirm(amounts,cash)}>{t(busy?"confirming":"confirmAllocation")} <span>→</span></button><p className="model-note">{savingDraft?t("draftSaving"):t("cashSummary")}</p>
    </aside></div>{details&&<CompanyDetails company={details} onClose={()=>setDetails(null)}/>}
  </main>;
}

export function RoundResult({session,busy,error,onContinue}:{session:SessionResponse;busy:boolean;error:string;onContinue:()=>void}) {
  const {t,language}=useI18n();const r=session.result!;const max=Math.max(1,...r.companies.map(c=>Math.abs(c.resultingCents-c.amountCents)));
  return <main className="app-content result-page"><div className="page-heading"><h1>{t("roundDone",{round:r.roundNo})}</h1></div><section className="result-overview panel"><div><span>{t("before")}</span><strong>{formatMoneyExact(r.capitalBeforeCents,language)}</strong></div><div className="result-main"><span>{t("after")}</span><strong><AnimatedMoney cents={r.capitalAfterCents} from={r.capitalBeforeCents}/></strong></div><div><span>{t("change")}</span><strong className={r.profitCents>=0?"is-positive":"is-negative"}>{formatMoneySignedExact(r.profitCents,language)}</strong></div></section><section className="result-company-list">{r.companies.map((c,i)=>{const profit=c.resultingCents-c.amountCents;return <article className="result-company panel" key={c.startupId} style={{animationDelay:`${i*60}ms`}}><div className="company-heading"><BrandIcon id={c.startupId}/><h2>{c.startupId}</h2><strong className={c.returnBps>=0?"is-positive":"is-negative"}>{formatPercent(c.returnBps,language)}</strong></div><p className="result-event">{c.event[language]}</p><details className="result-detail"><summary>{t("resultDetails")}</summary><p className="result-explanation">{c.explanation?.[language]}</p></details><div className="contribution-heading"><span>{t("contribution")}</span><strong className={profit>=0?"is-positive":"is-negative"}>{formatMoneySignedExact(profit,language)}</strong></div><div className="contribution-bar"><span style={{width:`${Math.abs(profit)*100/max}%`,background:profit>=0?"#24846b":"#bf595b"}}/></div><div className="result-values"><span>{formatMoneyExact(c.amountCents,language)}</span><span>→</span><strong>{formatMoneyExact(c.resultingCents,language)}</strong></div></article>;})}</section>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="result-actions"><button className="primary-button" disabled={busy} onClick={onContinue}>{t(busy?"wait":r.roundNo===3?"finishGame":"nextRound")} →</button></div></main>;
}
export function SessionFinal({session,onNext}:{session:SessionResponse;onNext:()=>void}) {
  const {t,language}=useI18n();const capital=session.finalCapitalCents!,report=session.report;const profit=capital-100000;
  return <main className="app-content final-player-page"><section className="final-hero"><div><p className="player-caption">{session.name}</p><h1>{t("finishTitle")}</h1><div className="final-stats"><div><span>{t("finalCapital")}</span><strong><AnimatedMoney cents={capital} from={100000}/></strong></div><div><span>{t("gain")}</span><strong className={profit>=0?"is-positive":"is-negative"}>{formatPercent(Math.round(profit/10),language)}</strong></div></div><div className="final-next"><button className="primary-button" onClick={onNext}>{t("continueToStart")} →</button><span>{t("resetHint")}</span></div></div><div className="place-medallion"><span>{t("celebration")}</span><strong>{session.place}</strong><div className="medallion-orbit"/></div></section>
    <div className="report-grid"><section className="panel"><h2>{t("seriesChart")}</h2><LineChart large values={[100000,...session.capitalHistory.map(p=>p.capitalCents)]} label={session.capitalHistory.map(p=>`${p.roundNo}: ${formatMoneyExact(p.capitalCents,language)}`).join("; ")}/><div className="chart-labels">{[100000,...session.capitalHistory.map(p=>p.capitalCents)].map((v,i)=><span key={i}><strong>{formatMoneyExact(v,language)}</strong><small>{i?t("previousValue",{round:i}):t("yourStart")}</small></span>)}</div></section>{report&&<section className="panel"><h2>{t("yourReport")}</h2><div className="report-kpis"><div><span>{t("bestRound")}</span><strong>{report.bestRound} <small>{formatMoneySignedExact(report.bestRoundProfitCents,language)}</small></strong></div><div><span>{t("averageCash")}</span><strong>{formatPercent(report.averageCashBps,language,false)}</strong></div><div><span>{t("maxPosition")}</span><strong>{formatPercent(report.maximumConcentrationBps,language,false)}</strong></div></div>{report.observations.map((o,i)=><p className="insight" key={i}>{o[language]}</p>)}</section>}</div>
    <details className="final-detail panel"><summary>{t("yourJourney")}</summary>{report&&<section><h2>{t("contribution")}</h2><div className="final-contributors">{report.contributors.map(c=><div key={c.startupId}><BrandIcon id={c.startupId} size={32}/><span>{c.startupId}</span><strong className={c.profitCents>=0?"is-positive":"is-negative"}>{formatMoneySignedExact(c.profitCents,language)}</strong></div>)}</div></section>}
    <section className="journey-panel"><div className="journey-grid">{session.roundHistory.map(r=><div key={r.roundNo}><h3>{t("allocationRound",{round:r.roundNo})}</h3><PortfolioBar amounts={Object.fromEntries(STARTUP_IDS.map(id=>[id,r.companies.find(c=>c.startupId===id)?.amountCents??0])) as Record<StartupId,number>} cash={r.cashCents} capital={r.capitalBeforeCents} ids={session.startupIds}/><p>{formatMoneyExact(r.capitalBeforeCents,language)} → {formatMoneyExact(r.capitalAfterCents,language)}</p></div>)}</div></section></details>
  </main>;
}
