import { useEffect, useRef, useState, type FormEvent } from "react";
import type { OrganizerOverview, PublicEventResponse } from "@startup-game/shared";
import { api, ApiClientError } from "./api.js";
import { useI18n } from "./i18n.js";

export function Organizer({ onClose, onEvent, onReplay, onFinalize }: { onClose:()=>void;onEvent:(e:PublicEventResponse)=>void;onReplay:()=>void;onFinalize:()=>void }) {
  const {t}=useI18n();const ref=useRef<HTMLDialogElement>(null);const [token,setToken]=useState("");const [password,setPassword]=useState("");const [overview,setOverview]=useState<OrganizerOverview|null>(null);const [title,setTitle]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [saved,setSaved]=useState(false);
  useEffect(()=>{ref.current!.showModal();return()=>ref.current?.close();},[]);
  const message=(e:unknown)=>e instanceof ApiClientError?t(e.code==="INVALID_ORGANIZER_PASSWORD"?"badPassword":e.code==="ORGANIZER_PASSWORD_NOT_CONFIGURED"?"passwordNotConfigured":e.code==="ORGANIZER_AUTH_REQUIRED"?"authExpired":e.status===0?"networkError":"genericError"):t("genericError");
  const accept=(v:OrganizerOverview)=>{setOverview(v);setTitle(v.event.title);onEvent(v.event);};
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const login=await api.organizerLogin(password);setPassword("");setToken(login.token);accept(await api.organizer(login.token));}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function action(fn:()=>Promise<OrganizerOverview|void>){setBusy(true);setError("");setSaved(false);try{const result=await fn();if(result)accept(result);setSaved(true);}catch(e){setError(message(e));if(e instanceof ApiClientError&&e.status===401){setToken("");setOverview(null);}}finally{setBusy(false);}}
  return <dialog ref={ref} className="organizer-dialog" onCancel={onClose} aria-labelledby="organizer-title"><div className="dialog-content"><button className="close-dialog" onClick={onClose} aria-label={t("cancel")}>×</button><h2 id="organizer-title">{t("cabinet")}</h2>{!overview?<form onSubmit={login}><label htmlFor="dashboard-password">{t("organizerPassword")}</label><input id="dashboard-password" type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} required/><div className="dialog-actions"><button className="secondary-button" type="button" onClick={onClose}>{t("cancel")}</button><button className="primary-button" disabled={busy}>{t(busy?"wait":"login")}</button></div></form>:<>
    <div className="organizer-stats"><div><span>{t(overview.event.status==="OPEN"?"eventOpen":"eventClosed")}</span><strong>{overview.event.completedCount}</strong><small>{t("playerCount",{count:overview.event.completedCount})}</small></div><div><span>{t("activePlayers")}</span><strong>{overview.activePlayers}</strong></div><div><span>{t("version")}</span><strong>v{overview.modelVersion}</strong></div></div>
    <form onSubmit={e=>{e.preventDefault();void action(()=>api.renameEvent(token,title));}}><label htmlFor="event-title">{t("eventTitle")}</label><input id="event-title" minLength={2} maxLength={60} value={title} disabled={overview.event.status!=="OPEN"||busy} onChange={e=>setTitle(e.target.value)}/><button className="secondary-button" disabled={overview.event.status!=="OPEN"||busy}>{t("saveTitle")}</button></form>
    <div className="organizer-tools"><button className="secondary-button" disabled={busy} onClick={()=>void action(()=>api.download(token,"ranking.csv"))}>{t("exportCsv")} ↓</button><button className="secondary-button" disabled={busy} onClick={()=>void action(()=>api.download(token,"backup.sqlite"))}>{t("backup")} ↓</button></div>
    {overview.event.status==="OPEN"?<button className="primary-button" disabled={busy||overview.activePlayers>0} onClick={()=>{onClose();onFinalize();}}>{t("organizer")}</button>:<><button className="secondary-button" onClick={()=>{onClose();onReplay();}}>{t("replay")}</button><button className="primary-button" disabled={busy} onClick={()=>void action(()=>api.newEvent(token,title))}>{t("newEvent")} →</button><p className="model-note">{t("newEventHint")}</p></>}
    <button className="quiet-button" onClick={()=>{setToken("");setOverview(null);setPassword("");}}>{t("logout")}</button></>}{error&&<p className="inline-error" role="alert">{error}</p>}{saved&&<p className="is-positive" role="status">{t("saved")}</p>}</div></dialog>;
}
